# Build stage
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN --mount=type=cache,id=global-npm-cache,sharing=locked,target=/root/.npm npm ci

COPY . .

RUN npx prisma generate

RUN npm run build

# Production stage
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

COPY --from=builder /app/node_modules ./node_modules
RUN npm prune --production

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/dist-seed ./dist-seed
COPY --from=builder /app/prisma ./prisma

ENV NODE_ENV=production

EXPOSE 8019

CMD npx prisma migrate deploy && npm run seed:prod && node dist/main
